### ISSUE TITLE
Using back and forward buttons does not change slide

### ISSUE THREAD

**Issue by rajsite** [notwaldorf/literally#4]
It looks like slide transitions have pushState because hitting back and forward changes the current slide number in the url fragment, but the slides themselves do not change

![animation](https://cloud.githubusercontent.com/assets/1588923/17596990/7e5987ea-5fb9-11e6-9f38-2e2823ff423f.gif)

**Comment by notwaldorf** [comment]
Yeah, I didn't add a listener for `hashchange`, so if you just change the hash but don't refresh the page, it doesn't advance the slide
